server:
  port: 8008
  tomcat:
    uri-encoding: UTF-8 # character encoding to use for URL decoding
    max-http-post-size: 1024
#wx:
#  open:
#    config:
#      appid:
#      secret:
#      redirectUrl: http://www.xxx.com/wxCallBack
#      csfKey: WeChat_WxJava_Demo
appsecret: a95107d86eba2432f56079f6ab83d164
#微信开放平台创建的网站应用的appid
appid: wx9557062a91dca7fb
scope: snsapi_login
#微信开放平台创建的网站 设置的授权回调域
callBack: https://mdt.knowimage.cn:8008/callBack
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    #数据库索引
    database: 2
    host: 192.168.50.244
    port: 6379
    password:
    #连接超时时间
    timeout: 5000

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2
